services:
  - type: web
    name: queue-manager
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
